---
apiVersion: v1
kind: Service
metadata:
  name: micro-api
  namespace: default
  labels:
    name: micro-api
spec:
  ports:
  # the port that this service should serve on
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: micro-api
  type: LoadBalancer
