---
apiVersion: v1
kind: Service
metadata:
  name: micro-web
  namespace: default
  labels:
    name: micro-web
spec:
  ports:
    # the port that this service should serve on
    - name: http
      port: 80
      targetPort: 8082
      nodePort: 30003
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: micro-web
  type: LoadBalancer
